eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_HOST:http://localhost:8761/eureka}
